#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════
# MPC Wallet — Local Infrastructure (1-shot)
#
# Spins up Vault + Redis + Gateway on localhost for testing.
# Everything auto-provisions: Vault secrets, AppRole, Redis, Gateway.
#
# Usage:
#   ./scripts/local-infra.sh          # start everything
#   ./scripts/local-infra.sh down     # tear down
#   ./scripts/local-infra.sh status   # check health
#   ./scripts/local-infra.sh logs     # tail gateway logs
# ═══════════════════════════════════════════════════════════════════════

set -euo pipefail

COMPOSE_FILE="infra/docker/docker-compose.local.yml"
PROJECT_NAME="mpc-local"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

log()  { echo -e "${GREEN}[+]${NC} $1"; }
warn() { echo -e "${YELLOW}[!]${NC} $1"; }
err()  { echo -e "${RED}[x]${NC} $1"; exit 1; }
step() { echo -e "\n${CYAN}━━━ $1 ━━━${NC}"; }

# ── Subcommands ───────────────────────────────────────────────────────

case "${1:-up}" in
  down|stop)
    step "Tearing down local infra"
    docker compose -p "$PROJECT_NAME" -f "$COMPOSE_FILE" down -v 2>/dev/null || true
    log "Done. All containers and volumes removed."
    exit 0
    ;;
  status)
    step "Service status"
    docker compose -p "$PROJECT_NAME" -f "$COMPOSE_FILE" ps
    echo ""
    echo "Health checks:"
    curl -sf http://localhost:8200/v1/sys/health | jq -r '"  Vault:   \(.initialized) / sealed=\(.sealed)"' 2>/dev/null || echo "  Vault:   not running"
    curl -sf http://localhost:6379 2>/dev/null && echo "  Redis:   ok" || echo "  Redis:   not running"
    curl -sf http://localhost:3000/v1/health | jq -r '"  Gateway: \(.data.status) (chains=\(.data.chains_supported))"' 2>/dev/null || echo "  Gateway: not running"
    exit 0
    ;;
  logs)
    docker compose -p "$PROJECT_NAME" -f "$COMPOSE_FILE" logs -f gateway
    exit 0
    ;;
  up) ;; # fall through to main flow
  *)
    echo "Usage: $0 [up|down|status|logs]"
    exit 1
    ;;
esac

# ── Prerequisites ─────────────────────────────────────────────────────

step "Checking prerequisites"

command -v docker >/dev/null 2>&1 || err "docker not found"
command -v curl >/dev/null 2>&1   || err "curl not found"
command -v jq >/dev/null 2>&1     || err "jq not found — brew install jq"
docker info >/dev/null 2>&1       || err "Docker daemon not running"

log "Prerequisites OK"

# ── Generate compose file ─────────────────────────────────────────────

step "Generating docker-compose for local infra"

mkdir -p "$(dirname "$COMPOSE_FILE")"

cat > "$COMPOSE_FILE" << 'COMPOSEFILE'
# Auto-generated by scripts/local-infra.sh — do not edit manually
# Vault (dev) + Redis + NATS + API Gateway

services:
  # ── HashiCorp Vault (dev mode) ──────────────────────────────────
  vault:
    image: hashicorp/vault:1.15
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "dev-root-token"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    cap_add:
      - IPC_LOCK
    healthcheck:
      test: ["CMD", "vault", "status", "-address=http://127.0.0.1:8200"]
      interval: 5s
      timeout: 3s
      retries: 10

  # ── Redis ───────────────────────────────────────────────────────
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 128mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  # ── NATS (MPC transport) ────────────────────────────────────────
  nats:
    image: nats:2.10-alpine
    ports:
      - "4222:4222"
      - "8222:8222"
    command: -js --http_port 8222 --max_payload 1048576
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8222/healthz"]
      interval: 5s
      timeout: 3s
      retries: 10
COMPOSEFILE

log "Compose file written: $COMPOSE_FILE"

# ── Start infrastructure containers ──────────────────────────────────

step "Starting Vault + Redis + NATS"

docker compose -p "$PROJECT_NAME" -f "$COMPOSE_FILE" up -d

# Wait for healthy
log "Waiting for services to be healthy..."
for svc in vault redis nats; do
  for i in $(seq 1 30); do
    if docker compose -p "$PROJECT_NAME" -f "$COMPOSE_FILE" ps "$svc" 2>/dev/null | grep -q "healthy"; then
      log "$svc is healthy"
      break
    fi
    if [ "$i" -eq 30 ]; then
      err "$svc failed to become healthy after 30s"
    fi
    sleep 1
  done
done

# ── Provision Vault secrets ──────────────────────────────────────────

step "Provisioning Vault secrets"

export VAULT_ADDR="http://127.0.0.1:8200"
export VAULT_TOKEN="dev-root-token"

# Generate random secrets
JWT_SECRET=$(openssl rand -hex 32)
SERVER_SIGNING_KEY=$(openssl rand -hex 32)
SESSION_ENCRYPTION_KEY=$(openssl rand -hex 32)

# Write secrets to Vault KV v2
curl -sf -X POST "$VAULT_ADDR/v1/secret/data/mpc-wallet/gateway" \
  -H "X-Vault-Token: $VAULT_TOKEN" \
  -H "Content-Type: application/json" \
  -d "$(jq -n \
    --arg jwt "$JWT_SECRET" \
    --arg ssk "$SERVER_SIGNING_KEY" \
    --arg sek "$SESSION_ENCRYPTION_KEY" \
    '{data: {jwt_secret: $jwt, server_signing_key: $ssk, session_encryption_key: $sek, redis_url: "redis://redis:6379"}}'
  )" > /dev/null

log "Secrets written to Vault at secret/mpc-wallet/gateway"

# Verify secrets are readable
VERIFY=$(curl -sf "$VAULT_ADDR/v1/secret/data/mpc-wallet/gateway" \
  -H "X-Vault-Token: $VAULT_TOKEN" | jq -r '.data.data | keys | length')
log "Verified: $VERIFY secrets in Vault"

# ── Create AppRole (production pattern demo) ─────────────────────────

step "Creating AppRole for gateway"

# Enable AppRole auth (ignore if already enabled)
curl -sf -X POST "$VAULT_ADDR/v1/sys/auth/approle" \
  -H "X-Vault-Token: $VAULT_TOKEN" \
  -d '{"type": "approle"}' 2>/dev/null || true

# Create policy
curl -sf -X PUT "$VAULT_ADDR/v1/sys/policies/acl/mpc-gateway" \
  -H "X-Vault-Token: $VAULT_TOKEN" \
  -d '{"policy": "path \"secret/data/mpc-wallet/*\" { capabilities = [\"read\"] }"}' > /dev/null

# Create role
curl -sf -X POST "$VAULT_ADDR/v1/auth/approle/role/mpc-gateway" \
  -H "X-Vault-Token: $VAULT_TOKEN" \
  -d '{"token_policies": ["mpc-gateway"], "token_ttl": "1h", "token_max_ttl": "4h"}' > /dev/null

# Get role_id and secret_id
ROLE_ID=$(curl -sf "$VAULT_ADDR/v1/auth/approle/role/mpc-gateway/role-id" \
  -H "X-Vault-Token: $VAULT_TOKEN" | jq -r '.data.role_id')

SECRET_ID=$(curl -sf -X POST "$VAULT_ADDR/v1/auth/approle/role/mpc-gateway/secret-id" \
  -H "X-Vault-Token: $VAULT_TOKEN" | jq -r '.data.secret_id')

log "AppRole created: role_id=$ROLE_ID"

# ── Build and run the gateway ────────────────────────────────────────

step "Building API gateway"

cargo build --release -p mpc-wallet-api 2>&1 | tail -3

step "Starting API gateway (Vault + Redis)"

# Kill any existing gateway
pkill -f "mpc-wallet-api" 2>/dev/null || true
sleep 1

# Start gateway with Vault backend
SECRETS_BACKEND=vault \
VAULT_ADDR=http://127.0.0.1:8200 \
VAULT_ROLE_ID="$ROLE_ID" \
VAULT_SECRET_ID="$SECRET_ID" \
NETWORK=testnet \
SESSION_BACKEND=redis \
REDIS_URL=redis://127.0.0.1:6379 \
RUST_LOG=mpc_wallet_api=info \
  ./target/release/mpc-wallet-api &

GATEWAY_PID=$!
log "Gateway started (PID: $GATEWAY_PID)"

# Wait for gateway to be ready
for i in $(seq 1 15); do
  if curl -sf http://localhost:3000/v1/health > /dev/null 2>&1; then
    break
  fi
  if [ "$i" -eq 15 ]; then
    err "Gateway failed to start after 15s"
  fi
  sleep 1
done

# ── Smoke test ───────────────────────────────────────────────────────

step "Smoke test"

echo ""
echo "  Health check:"
curl -sf http://localhost:3000/v1/health | jq '.'

echo ""
echo "  Chains (first 3):"
curl -sf http://localhost:3000/v1/chains | jq '.data.chains[:3]'

echo ""
echo "  Auth (no token → expect AUTH_FAILED):"
curl -sf http://localhost:3000/v1/wallets 2>/dev/null | jq '.error' || \
  curl -s http://localhost:3000/v1/wallets | jq '.error'

# ── Summary ──────────────────────────────────────────────────────────

step "Local infrastructure ready"

echo ""
echo -e "  ${GREEN}Vault${NC}     http://localhost:8200  (token: dev-root-token)"
echo -e "  ${GREEN}Redis${NC}     redis://localhost:6379"
echo -e "  ${GREEN}NATS${NC}      nats://localhost:4222   (monitor: http://localhost:8222)"
echo -e "  ${GREEN}Gateway${NC}   http://localhost:3000   (PID: $GATEWAY_PID)"
echo ""
echo -e "  Vault UI:  ${CYAN}http://localhost:8200/ui${NC}"
echo -e "  Secrets:   ${CYAN}secret/mpc-wallet/gateway${NC} (jwt_secret, server_signing_key, session_encryption_key, redis_url)"
echo ""
echo -e "  ${YELLOW}Tear down:${NC}  ./scripts/local-infra.sh down && kill $GATEWAY_PID"
echo ""
echo -e "  Test handshake:"
echo -e "    curl -s http://localhost:3000/v1/health | jq ."
echo -e "    curl -s http://localhost:3000/v1/chains | jq .data.total"
echo ""
